services:
  am-store-api:
    container_name: am-store-server-production-mode
    image: abdulrahmangoni/am-store-server
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    env_file:
      - .env.secret
      - .env.db.secret.prod
    command: npm start
    ports:
      - "7000:7000"